# Generated by Django 3.1 on 2021-08-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=220)),
                ('last_name', models.CharField(max_length=220)),
                ('profile', models.ImageField(upload_to='photo/%y/%m/%d')),
                ('job', models.CharField(max_length=220)),
                ('face_link', models.URLField(max_length=220)),
                ('twitter_link', models.URLField(max_length=220)),
                ('google_link', models.URLField(max_length=220)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
